### ISSUE TITLE
求助！该项目中的环境变量

### ISSUE THREAD

**Issue by ymj68520** [ethanysc-git/dragon-mint#1]
该项目中引用了一个名为`NEXT_PUBLIC_SUBGRAPH_URL`环境变量，你能详细介绍一下这个变量吗？

**Comment by ethanysc-git** [comment]
你好, 
方便請問一下你是誰嗎(可選)
下面回答你的問題
首先這個repo並非 [https://www.dragon-mint-anan.dev/](https://www.dragon-mint-anan.dev/)實際對應的repo，但兩者均由我在維護，雖然這個repo暫時沒有要同步到最新，所以你實際運作起來後，畫面跟功能會不一樣
接著是NEXT_PUBLIC_SUBGRAPH_URL環境變量
NEXT_PUBLIC_SUBGRAPH_URL環境變量是我為記錄合約DragonMintMarketplace的event配置的
是屬於the graph提供的服務之一，[https://thegraph.com/studio/](https://thegraph.com/studio/)
可以參考[https://thegraph.com/docs/en/developing/creating-a-subgraph/](https://thegraph.com/docs/en/developing/creating-a-subgraph/)，該NEXT_PUBLIC_SUBGRAPH_URL便是用在使用api, fetch
使用時要用到一些typescript跟graphql，不熟悉的話，建議使用預設的模式，文件介紹很詳細

**Comment by ymj68520** [comment]
我是一名正在学习该方向的学生，感谢您的帮助！

**Comment by ethanysc-git** [comment]
謝謝你對專案感興趣
雖然不知道有沒有幫助
不過我可以簡單說明一下實際repo做出的改動
1.
首先是css部分，我移除了tailwind，我目前是自建每個component 對應的css.module，如果要使用css框架的話，我個人覺得StyleX會是個好選項
2. React component的拆分，最終我的每個page都僅由component構成，複雜的component由更小的component構成
以index.js來說，更改後的檔案
```
import React from "react";
import { HeroSection, Service } from "../components/componentindex";

function Home() {
  return (
    <div>
      <HeroSection />
      <Service />
    </div>
  );
}

export default Home;
```

其中共用的Header跟Footer當然也是額外拆出來
3. 新增的功能
(3-1)帳戶抽象
(3-2) ORA + ERC˙7007
用到的文檔如下 : 
(3-1)
[Particle Network](https://docs.particle.network/developers/account-abstraction) + [Biconomy](https://docs.biconomy.io/)
(3-2)
[ERC-7007: Verifiable AI-Generated Content Token](https://eips.ethereum.org/EIPS/eip-7007) 、 [ORA](https://docs.ora.io/doc)

希望對你的學習有一些幫助
